export const toolNames = {
  bash: "bash",
  copy: "copy",
  delete: "delete",
  edit: "edit",
  find: "find",
  grep: "grep",
  ls: "ls",
  mkdir: "mkdir",
  move: "move",
  policyInfo: "policy_info",
  read: "read",
  rg: "rg",
  stat: "stat",
  subagent: "subagent",
  subagentAwait: "subagent_await",
  subagentCancel: "subagent_cancel",
  subagentStatus: "subagent_status",
  write: "write",

  dockerBuild: "docker_build",
  dockerComposeDown: "docker_compose_down",
  dockerComposeUp: "docker_compose_up",
  dockerImages: "docker_images",
  dockerInspect: "docker_inspect",
  dockerLogs: "docker_logs",
  dockerPs: "docker_ps",
  dockerRm: "docker_rm",
  dockerStop: "docker_stop",
  gitAdd: "git_add",
  gitBranch: "git_branch",
  gitCheckout: "git_checkout",
  gitCommit: "git_commit",
  gitDiff: "git_diff",
  gitLog: "git_log",
  gitShow: "git_show",
  gitStash: "git_stash",
  gitStatus: "git_status",
  nodeExec: "node_exec",
  powershellExec: "powershell_exec",
  pythonExec: "python_exec",
  webLookup: "web_lookup",
} as const;

export type ToolName = typeof toolNames[keyof typeof toolNames];
